// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1pdXD04dBJEajNUS2XqBu0AhH_xNK_FY',
    appId: '1:1090992125173:web:aa9ac30f3dd74a971441bc',
    messagingSenderId: '1090992125173',
    projectId: 'my-notes-app-f2b2c',
    authDomain: 'my-notes-app-f2b2c.firebaseapp.com',
    storageBucket: 'my-notes-app-f2b2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Bo3VD36KU6_lOcFWk62vkt-woaTN4BY',
    appId: '1:1090992125173:android:a841b755616dfacf1441bc',
    messagingSenderId: '1090992125173',
    projectId: 'my-notes-app-f2b2c',
    storageBucket: 'my-notes-app-f2b2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVyJ7dNQ2wek2lKpxEupRJrOriAeTAkJQ',
    appId: '1:1090992125173:ios:3d91fb272f936a6b1441bc',
    messagingSenderId: '1090992125173',
    projectId: 'my-notes-app-f2b2c',
    storageBucket: 'my-notes-app-f2b2c.appspot.com',
    iosClientId: '1090992125173-1e2tv5vm5c7hvfibff9ivm7itodubure.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVyJ7dNQ2wek2lKpxEupRJrOriAeTAkJQ',
    appId: '1:1090992125173:ios:3d91fb272f936a6b1441bc',
    messagingSenderId: '1090992125173',
    projectId: 'my-notes-app-f2b2c',
    storageBucket: 'my-notes-app-f2b2c.appspot.com',
    iosClientId: '1090992125173-1e2tv5vm5c7hvfibff9ivm7itodubure.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
